services:
  cube:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ".env"
    labels:
      - traefik.enable=true
      - traefik.http.routers.cube.rule=Host(`cube.${DOMAIN}`)
      - traefik.http.routers.cube.entrypoints=websecure
      - traefik.http.routers.cube.tls=true
    networks:
      - webgateway
    command: "npm run start"
    volumes:
      - ./:/app

networks:
  webgateway:
    name: ${NETWORK}
    external: true


